version: "3"
services:

  criptop2p:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mysqldb
      - redis-cache

  mysqldb:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis-cache:
    image: redis:alpine
    networks:
      - backend

networks:
  backend:
